name: Testing
on: [push]
jobs:
  e2e-chrome:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          command: |
            npm run e2e:headless
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots-in-headless-chrome
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        with:
          name: video-in-headless-chrome
          path: cypress/videos
  # e2e-firefox:
  #   runs-on: ubuntu-latest
  #   # let's make sure our tests pass on Chrome browser
  #   name: E2E on Firefox
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cypress-io/github-action@v2
  #       with:
  #         browser: firefox
  #         command: |
  #           npm run e2e
  #     - uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: screenshots-in-headless-firefox
  #         path: cypress/screenshots
  #     - uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: video-in-headless-firefox
  #         path: cypress/videos
  # e2e-edge:
  #   runs-on: windows-latest
  #   # let's make sure our tests pass on Chrome browser
  #   name: E2E on Edge
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cypress-io/github-action@v2
  #       with:
  #         browser: edge
  #         command: |
  #           npm run e2e
  #     - uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: screenshots-in-headless-edge
  #         path: cypress/screenshots
  #     - uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: video-in-headless-edge
  #         path: cypress/videos